import type { Localization } from "@better-auth-ui/core";

export const viLocalization: Localization = {
  auth: {
    account: "Tài khoản",
    alreadyHaveAnAccount: "Đã có tài khoản?",
    alreadyVerifiedYourEmail: "Đã xác thực email?",
    confirmPassword: "Xác nhận mật khẩu",
    confirmPasswordPlaceholder: "Xác nhận mật khẩu của bạn",
    checkYourEmail: "Kiểm tra email của bạn để nhận liên kết xác thực",
    checkYourEmailTitle: "Kiểm tra email",
    continueWith: "Tiếp tục với {{provider}}",
    email: "Email",
    emailPlaceholder: "m@example.com",
    fieldRequired: "Trường này là bắt buộc",
    forgotPassword: "Quên mật khẩu",
    forgotPasswordLink: "Quên mật khẩu?",
    hidePassword: "Ẩn mật khẩu",
    invalidEmail: "Vui lòng nhập địa chỉ email hợp lệ",
    invalidResetPasswordToken: "Mã đặt lại mật khẩu không hợp lệ",
    name: "Tên",
    namePlaceholder: "Tên",
    needToCreateAnAccount: "Chưa có tài khoản?",
    newPassword: "Mật khẩu mới",
    newPasswordPlaceholder: "Mật khẩu mới",
    openEmailProvider: "Mở {{provider}}",
    or: "HOẶC",
    optional: " (không bắt buộc)",
    password: "Mật khẩu",
    passwordPlaceholder: "Mật khẩu",
    passwordResetEmailSent: "Đã gửi email đặt lại mật khẩu",
    passwordResetErrorDescription:
      "Không thể đặt lại mật khẩu. Vui lòng thử lại.",
    passwordResetSuccess: "Đặt lại mật khẩu thành công",
    passwordResetSuccessDescription:
      "Đặt lại mật khẩu thành công. Bạn có thể đăng nhập bằng mật khẩu mới.",
    passwordsDoNotMatch: "Mật khẩu không khớp",
    rememberMe: "Ghi nhớ đăng nhập",
    tooLong: "Tối đa {{max}} ký tự",
    tooShort: "Tối thiểu {{min}} ký tự",
    rememberYourPassword: "Nhớ mật khẩu của bạn?",
    resend: "Gửi lại",
    resendIn: "Gửi lại sau {{seconds}}s",
    resetLinkSentTo: "Chúng tôi đã gửi liên kết đặt lại mật khẩu đến {{email}}",
    resetPassword: "Đặt lại mật khẩu",
    sendResetLink: "Gửi liên kết",
    scanToOpenEmailProvider: "Quét để mở {{provider}} trên điện thoại của bạn",
    showPassword: "Hiện mật khẩu",
    signIn: "Đăng nhập",
    signOut: "Đăng xuất",
    signUp: "Đăng ký",
    verificationEmailSent: "Đã gửi email xác thực!",
    verifyEmail: "Xác thực email",
  },
  settings: {
    account: "Tài khoản",
    accountUnlinked: "Hủy liên kết tài khoản",
    active: "Hoạt động",
    activeSessions: "Phiên hoạt động",
    avatar: "Ảnh đại diện",
    currentSession: "Phiên hiện tại",
    avatarChangedSuccess: "Đổi ảnh đại diện thành công",
    avatarDeletedSuccess: "Xóa ảnh đại diện thành công",
    changeAvatar: "Đổi ảnh đại diện",
    deleteAvatar: "Xóa ảnh đại diện",
    link: "Liên kết",
    linkedAccounts: "Tài khoản đã liên kết",
    linkProvider: "Liên kết tài khoản {{provider}}",
    cancel: "Hủy",
    copyToClipboard: "Sao chép vào khay nhớ tạm",
    changeEmail: "Đổi email",
    changeEmailSuccess: "Kiểm tra email để xác nhận thay đổi",
    changePassword: "Đổi mật khẩu",
    changePasswordSuccess: "Đổi mật khẩu thành công",
    currentPassword: "Mật khẩu hiện tại",
    currentPasswordPlaceholder: "Nhập mật khẩu hiện tại",
    dangerZone: "Khu vực nguy hiểm",
    delete: "Xóa",
    optional: "Không bắt buộc",
    profileUpdatedSuccess: "Cập nhật hồ sơ thành công",
    revoke: "Thu hồi",
    revokeSession: "Thu hồi phiên",
    revokeSessionSuccess: "Thu hồi phiên thành công",
    saveChanges: "Lưu thay đổi",
    setPassword: "Đặt mật khẩu",
    setPasswordDescription:
      "Bạn chưa có mật khẩu. Hãy yêu cầu liên kết đặt lại để tạo.",
    security: "Bảo mật",
    settings: "Cài đặt",
    time: "Thời gian",
    unlinkProvider: "Hủy liên kết {{provider}}",
    updateEmail: "Cập nhật email",
    updatePassword: "Cập nhật mật khẩu",
    uploadAvatar: "Tải ảnh đại diện",
    userProfile: "Hồ sơ người dùng",
  },
};
